### ISSUE TITLE
Review: Summary

### ISSUE THREAD

**Issue by SidTheEngineer** [blairhardaker/Jammming#1]
✅ **Create React App**
Score: 1/1
Successfully set up the React app, including linking of fonts and removal of default logo

✅ **Component Creation**
Score: 1/1
Successfully set up component folders, used relative pathing, replaced hardcoded values, and appropriately used JSX. The only minor area for improvement here is in the amount of whitespace used in the JSX. We typically don't need a newline between each of the JSX elements. By not having extra newlines, we keep things concise and easier to reason about.

✅ **Search Results**
Score: 1/1
Successfully passed down search results to a `TrackList` component and provided an appropriate key for each of the `Track` components

✅ **Playlist**
Score: 1/1
Successfully passed down playlist tracks from the `Playlist` component to a `Tracklist` component to be rendered.

✅ **Add tracks to playlist**
Score: 1/1
Able to successfully add tracks to the playlist using the bound `addTrack` method without duplication of tracks

✅ **Remove tracks from playlist**
Score: 1/1
Able to successfully remove tracks from the playlist using a bound `removeTrack` method.

✅ **Change playlist name**
Score: 1/1
Playlist name changing works appropriately and makes use of the `defaultValue` attribute on the `<input>` element.

✅ **savePlaylist (App.js)**
Score: 1/1
Successfully set up a `savePlaylist` method in `App.js` and passed it down to the `Playlist` component to be used.

✅ **search (App.js)**
Score: 1/1
Successfully set up a `search` method in `App.js` and passed it down to the `SearchBar` component to be used.

✅ **getAccessToken**
Score: 1/1
Successfully set up the `getAccessToken` method in `Spotify.js` that allows the app to get authorization from a user.

✅ **search (Spotify.js)**
Score: 1/1
Searching is hooked up to Spotify and works perfectly. The method is set up correctly and returns the correct tracks given some query.

✅ **savePlaylist (Spotify.js)**
Score: 1/1
Able to successfully save playlists to a user's account using the `savePlaylist` method in `Spotify.js`.

## Overall Score: 12/12 🔥

**Comment by blairhardaker** [comment]
Thankyou. Appreciate the time you took to review the project.
